# Uncomment the next line to define a global platform for your project
platform :ios, '10.3.3'
source 'https://github.com/CocoaPods/Specs.git'
target '3D Mobile App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire', '~> 4.4'
  # Pods for 3D Mobile App

  target '3D Mobile AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '3D Mobile AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
