# Uncomment the next line to define a global platform for your project
platform :ios, '10.3.2'
source 'https://github.com/CocoaPods/Specs.git'
target '3DApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3DApp

  target '3DAppTests' do
   pod 'Alamofire', '~> 4.4'
    inherit! :search_paths
    # Pods for testing
  end

  target '3DAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
